import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync, mkdirSync } from "node:fs";
const selected = process.argv.slice(2);
const platforms = selected.length ? selected : ["android", "ios"];
if (platforms.some(platform => !["android", "ios"].includes(platform))) {
  throw new Error("Usage: npm run mobile:setup -- [android] [ios]");
}
const command = (name, args) => {
  const result = spawnSync(process.platform === "win32" ? name + ".cmd" : name, args, { stdio: "inherit" });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
};
// Capacitor 7 requires Node 20+; iOS builds require macOS and Xcode.
if (Number(process.versions.node.split(".")[0]) < 22) throw new Error("Use Node.js 22 or newer.");
command("npm", ["install", "@capacitor/core@7", "@capacitor/app@7", "@capacitor-community/admob@7",
  ...platforms.map(platform => "@capacitor/" + platform + "@7")]);
command("npm", ["install", "--save-dev", "@capacitor/cli@7"]);
mkdirSync("client/src/platform", { recursive: true });
writeFileSync("client/src/platform/native-installed.ts", [
  "// Generated by npm run mobile:setup. Commit with the generated dependency lockfile.",
  'export { App } from "@capacitor/app";',
  'export { AdMob } from "@capacitor-community/admob";',
  "",
].join("\n"));
command("npm", ["run", "build"]);
for (const platform of platforms) {
  if (!existsSync(platform)) command("npx", ["cap", "add", platform]);
  command("npx", ["cap", "sync", platform]);
}
console.log("Native projects generated. Configure AdMob application IDs, signing and billing before release. See docs/MOBILE_SETUP.md.");
