import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
const selected = process.argv.slice(2);
const platforms = selected.length ? selected : ["android", "ios"];
if (platforms.some(platform => !["android", "ios"].includes(platform))) {
  throw new Error("Usage: npm run mobile:setup -- [android] [ios]");
}
const command = (name, args) => {
  const result = spawnSync(process.platform === "win32" ? name + ".cmd" : name, args, { stdio: "inherit" });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
};
// Capacitor 7 requires Node 20+; iOS builds require macOS and Xcode.
if (Number(process.versions.node.split(".")[0]) < 22) throw new Error("Use Node.js 22 or newer.");
command("npm", ["install", "@capacitor/core@7", "@capacitor/app@7", "@capacitor-community/admob@7", "@capacitor/preferences@7", "@revenuecat/purchases-capacitor@11",
  ...platforms.map(platform => "@capacitor/" + platform + "@7")]);
command("npm", ["install", "--save-dev", "@capacitor/cli@7"]);
mkdirSync("client/src/platform", { recursive: true });
writeFileSync("client/src/platform/native-installed.ts", [
  "// Generated by npm run mobile:setup. Commit with the generated dependency lockfile.",
  'import { App as NativeApp } from "@capacitor/app";',
  'import { AdMob as NativeAdMob, MaxAdContentRating } from "@capacitor-community/admob";',
  'import type { NativeServices } from "./mobile";',
  'import { Purchases as NativePurchases, PRODUCT_CATEGORY } from "@revenuecat/purchases-capacitor";',
  'import { Preferences as NativePreferences } from "@capacitor/preferences";',
  'export const Preferences: NativeServices["Preferences"] = NativePreferences;',
  'export const Purchases: NativeServices["Purchases"] = {',
  '  configure: options => NativePurchases.configure(options),',
  '  logIn: options => NativePurchases.logIn(options),',
  '  getProducts: options => NativePurchases.getProducts({ ...options, type: PRODUCT_CATEGORY.NON_SUBSCRIPTION }),',
  '  purchaseProduct: async ({ productIdentifier }) => {',
  '    const { products } = await NativePurchases.getProducts({ productIdentifiers: [productIdentifier], type: PRODUCT_CATEGORY.NON_SUBSCRIPTION });',
  '    const product = products.find(item => item.identifier === productIdentifier);',
  '    if (!product) throw new Error("This heart pack is unavailable in the store.");',
  '    return NativePurchases.purchaseStoreProduct({ product, googleIsPersonalizedPrice: false });',
  '  },',
  '  restorePurchases: () => NativePurchases.restorePurchases(),',
  '};',
  'export const App: NativeServices["App"] = NativeApp;',
  'export const AdMob: NativeServices["AdMob"] = {',
  '  initialize: options => NativeAdMob.initialize({',
  '    initializeForTesting: options.initializeForTesting,',
  '    tagForChildDirectedTreatment: true, tagForUnderAgeOfConsent: true,',
  '    maxAdContentRating: MaxAdContentRating.General,',
  '  }),',
  '  prepareInterstitial: options => NativeAdMob.prepareInterstitial(options),',
  '  showInterstitial: () => NativeAdMob.showInterstitial(),',
  '  prepareRewardVideoAd: options => NativeAdMob.prepareRewardVideoAd(options),',
  '  showRewardVideoAd: () => NativeAdMob.showRewardVideoAd(),',
  '};',
  "",
].join("\n"));
command("npm", ["run", "build:client"]);
for (const platform of platforms) {
  if (!existsSync(platform)) command("npx", ["cap", "add", platform]);
  // Newly generated shells use only Google's sample application IDs. Preserve
  // existing IDs on repeat runs. Production identifiers require explicit release configuration.
  if (platform === "android") {
    const manifestPath = "android/app/src/main/AndroidManifest.xml";
    const manifest = readFileSync(manifestPath, "utf8");
    if (!manifest.includes("com.google.android.gms.ads.APPLICATION_ID")) {
      writeFileSync(manifestPath, manifest.replace("</application>",
        '<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713" />\n    </application>'));
    }
  } else {
    const plistPath = "ios/App/App/Info.plist";
    const plist = readFileSync(plistPath, "utf8");
    if (!plist.includes("GADApplicationIdentifier")) {
      writeFileSync(plistPath, plist.replace("</dict>\n</plist>",
        '<key>GADApplicationIdentifier</key>\n<string>ca-app-pub-3940256099942544~1458002511</string>\n</dict>\n</plist>'));
    }
  }
  command("npx", ["cap", "sync", platform]);
}
console.log("Native projects generated. Configure AdMob application IDs, signing and billing before release. See docs/MOBILE_SETUP.md.");
